const TECH_SKILL_TERMS = [
  '.net',
  'ai',
  'algorithm',
  'analytics',
  'android',
  'angular',
  'api',
  'application',
  'architecture',
  'automation',
  'aws',
  'azure',
  'backend',
  'bash',
  'big data',
  'blockchain',
  'c++',
  'c#',
  'ci/cd',
  'cloud',
  'code',
  'coding',
  'computer',
  'container',
  'css',
  'cyber',
  'data',
  'database',
  'devops',
  'django',
  'docker',
  'etl',
  'express',
  'fastapi',
  'flutter',
  'frontend',
  'gcp',
  'git',
  'golang',
  'graphql',
  'html',
  'ios',
  'java',
  'javascript',
  'kafka',
  'kotlin',
  'kubernetes',
  'langchain',
  'linux',
  'machine learning',
  'microservice',
  'mongodb',
  'mysql',
  'next.js',
  'node',
  'openai',
  'postgres',
  'programming',
  'python',
  'rabbitmq',
  'react',
  'redis',
  'rest',
  'ruby',
  'rust',
  'salesforce',
  'scala',
  'script',
  'security',
  'software',
  'spring',
  'sql',
  'swift',
  'tailwind',
  'terraform',
  'testing',
  'typescript',
  'ui',
  'ux',
  'vue',
  'web',
];

const NON_TECH_SKILL_TERMS = [
  'agriculture',
  'beauty',
  'carpentry',
  'cleaning',
  'cooking',
  'dance',
  'driving',
  'fashion',
  'food',
  'gardening',
  'healthcare',
  'hospitality',
  'language teaching',
  'legal',
  'medical',
  'music',
  'nursing',
  'painting',
  'retail',
  'sales technique',
  'sewing',
  'sports',
  'tourism',
  'welding',
];

export function isLikelyTechSkill(skill: string) {
  const normalized = normalizeSkillText(skill);
  if (!normalized) return false;

  const hasTechSignal = TECH_SKILL_TERMS.some((term) => hasSkillTerm(normalized, term));
  if (!hasTechSignal) return false;

  return !NON_TECH_SKILL_TERMS.some((term) => hasSkillTerm(normalized, term));
}

function normalizeSkillText(value: string) {
  return value.toLowerCase().replace(/\s+/g, ' ').trim();
}

function hasSkillTerm(value: string, term: string) {
  const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(^|[^a-z0-9+#.])${escaped}([^a-z0-9+#.]|$)`, 'i').test(value);
}
